name: Safari Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test_suite_Safari: # Name of the job
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.15.0' # In command line run "node -v" and choose your version

      - name: Install dependencies for Node.js
        run: npm ci # Uses package-lock.json to install dependencies exactly as specified, ensuring deterministic and reproducible builds

      - name: Installing XQuartz
        run: brew install --cask xquartz

      - name: Start XQuartz
        run: open -a "/Applications/Utilities/XQuartz.app"

      - name: Set the DISPLAY environment variable
        run: export DISPLAY=:0

      - name: Run Tests
        run: # Run your test command here
          npm run wdio 
